# QUICK START:
docker build -t flask_test .; docker run -it --rm  --publish 5000:5000 flask_test

# MANUAL start
docker build -t flask_test .; docker run -it --rm --entrypoint='' --publish 5000:5000 flask_test /bin/bash

# list all containers
docker ps -a

https://docs.docker.com/develop/develop-images/dockerfile_best-practices/
